name: Build & Release Zips
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create plugin zips
        run: |
          set -eux
          mkdir -p dist
          if [ -d "plugins/wp-omikuji-stripe" ]; then
            (cd plugins && zip -r ../dist/wp-omikuji-stripe-${GITHUB_REF_NAME}.zip wp-omikuji-stripe)
          fi
          if [ -d "plugins/wp-omikuji-stripe-pro" ]; then
            (cd plugins && zip -r ../dist/wp-omikuji-stripe-pro-${GITHUB_REF_NAME}.zip wp-omikuji-stripe-pro)
          fi
          ls -lh dist

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            dist/wp-omikuji-stripe-${{ github.ref_name }}.zip
            dist/wp-omikuji-stripe-pro-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

