name: PHP Lint
on:
  pull_request:
  push:
    branches: [ main, dev ]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PHP
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli
      - name: Lint PHP files
        run: |
          set -e
          mapfile -t files < <(git ls-files '*.php')
          for f in "${files[@]}"; do
            echo "Linting $f"
            php -l "$f"
          done

